In [1]:
import numpy as np
import seaborn as sns

In [2]:
X = [1.7, 2.1, 3.5, 3.9, 5, 6.5, 2.5, 3.5, 4, 5, 1, 6.6, 4.5,5.5, 3]
Y = [139,150,160,162,161,170,152,154,162,160,135,171,157,160,150]
X = np.array(X)
Y = np.array(Y)
w1 = (np.mean(X)*np.mean(Y) - np.mean(X*Y)) / (np.mean(X)**2- np.mean(X**2))
w1

5.483699928163382

In [3]:
w0 = np.mean(Y) - w1*np.mean(X)
w0

134.88668627920498

In [4]:
Y_ = w0 + w1*X
Y_

array([144.20897616, 146.40245613, 154.07963603, 156.273116  ,
       162.30518592, 170.53073581, 148.5959361 , 154.07963603,
       156.82148599, 162.30518592, 140.37038621, 171.07910581,
       159.56333596, 165.04703588, 151.33778606])

In [5]:
sns.scatterplot(X,Y);
sns.lỉnearplot(X,Y_)

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 were given

In [ ]:
import pandas as pd
data = pd.read_csv("data.csv")
data

In [ ]:
sns.scatterplot(data = data, y = 'price', x = 'sqft_living');

In [ ]:
sns.lmplot(data = data ,y = 'price', x= 'sqft_living')

In [ ]:
import scipy.stats as stats
stats.pearsonr(data.price,data.sqft_living)

In [ ]:
# Loại bỏ giá trị ngoại lai
from sklearn.preprocessing import RobustScaler as RS

#Lọc ngoại lai của price
Q1 = data['price'].quantile(0.25)
Q3 = data['price'].quantile(0.75)
IQR = Q3-Q1
data_price = data[~((data['price'] < (Q1 - 1.5 * IQR)) | (data['price'] > (Q3 + 1.5 * IQR)))]

#Lọc ngoại lai của sqft_living
Q1 = data_price['sqft_living'].quantile(0.25)
Q3 = data_price['sqft_living'].quantile(0.75)
IQR = Q3-Q1
data_price = data_price[~((data_price['sqft_living'] < (Q1 - 1.5 * IQR)) | (data_price['sqft_living'] > (Q3 + 1.5 * IQR)))]

import seaborn as sns
import numpy as np

X = data_price.loc[:,'sqft_living']
Y = data_price.loc[:,'price']

X = np.asarray(X)
Y = np.asarray(Y)

w1 = (X.mean()*Y.mean()- (X*Y).mean())/(X.mean()*X.mean()-(X*X).mean())
w0 = Y.mean()-w1*X.mean()
Y_ = w0 + w1*X
sns.scatterplot(x = X, y = Y)
sns.lineplot(x=X,y= Y_)

In [ ]:
dat = pd.read_csv("anscombe.csv")
dat

In [ ]:
import matplotlib.plot as plt
plt.scatter(dat['x'],dat['y'])

In [ ]:
#Demo 1 phân loại binary
import seaborn as sns
# example of binary classification task
from numpy import where
from collections import Counter
from sklearn.datasets import make_blobs
from matplotlib import pyplot
# define dataset
X, y = make_blobs(n_samples=200, centers=2, random_state=3)
# summarize dataset shape
print(X.shape, y.shape)
# summarize observations by class label
counter = Counter(y)
print(counter)
# summarize first few examples
for i in range(10):
    print(X[i], y[i])
# plot the dataset and color the by class label
for label, _ in counter.items():
    row_ix = where(y == label)[0]
    pyplot.scatter(X[row_ix, 0], X[row_ix, 1], label=str(label))
pyplot.legend()
pyplot.show()
sns.scatterplot(x=X[:,0], y=X[:,1], hue=Y);

In [ ]:
#Demo 3
# example of multi-class classification task
from numpy import where
from collections import Counter
from sklearn.datasets import make_blobs
from matplotlib import pyplot
# define dataset
X, y = make_blobs(n_samples=600, centers=2, random_state=3, cluster_std = 3.0)
# summarize dataset shape
print(X.shape, y.shape)
# summarize observations by class label
counter = Counter(y)
print(counter)
# summarize first few examples
for i in range(10):
    print(X[i], y[i])
# plot the dataset and color the by class label
for label, _ in counter.items():
    row_ix = where(y == label)[0]
    pyplot.scatter(X[row_ix, 0], X[row_ix, 1], label=str(label))
pyplot.legend()
pyplot.show()

In [ ]:
#Demo 2
# example of multi-class classification task
from numpy import where
from collections import Counter
from sklearn.datasets import make_blobs
from matplotlib import pyplot
# define dataset
X, Y = make_blobs(n_samples=600, centers=3, random_state=3)
# summarize dataset shape
print(X.shape, Y.shape)
# summarize observations by class label
counter = Counter(Y)
print(counter)
sns.scatterplot(x=X[:,0], y=X[:,1], hue=Y);

In [ ]:
#Demo 4
# example of an imbalanced binary classification task
from numpy import where
from collections import Counter
from sklearn.datasets import make_classification
from matplotlib import pyplot
# define dataset
X, y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, n_classes=2, n_clusters_per_class=1, weights=[0.99,0.01], random_state=1)
# summarize dataset shape
print(X.shape, y.shape)
# summarize observations by class label
counter = Counter(y)
print(counter)
# summarize first few examples
for i in range(10):
    print(X[i], y[i])
# plot the dataset and color the by class label
for label, _ in counter.items():
    row_ix = where(y == label)[0]
    pyplot.scatter(X[row_ix, 0], X[row_ix, 1], label=str(label))
pyplot.legend()
pyplot.show()

In [ ]:
#Predict giá trị
import numpy as np
x_ = [5, -2]
x_ = np.array(x_).reshape(1, -1)
# x_
y_ = logreg.predict(x_)
print(y_)
# Biểu diễn điểm này trên đồ thị
sns.scatterplot(x=X_test[:,0], y=X_test[:,1], hue=Y_test)
sns.scatterplot(x=x_[:,0], y=x_[:,1], color='r')
plt.show()
#Evaluate model
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

print('conf_m:', conf_m, sep='\n', end='\n\n')
sns.heatmap(conf_m)
plt.show()

print('report:', report, sep='\n')

In [ ]:
import pandas as pd
dat2 = pd.read_csv("IRIS.csv")
dat2

In [ ]:
from sklearn.model_selection import train_test_split

X = dat2.drop(columns='species',axis=1)
Y = dat2['species']

X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size=0.3) # 30% dữ liệu là test
print(X_train.shape)  # 120 records out of 150 will be the training data
print(X_test.shape)   #  30 records out of 150 will be the testing  data
#Tạo đối tượng model
logreg = LogisticRegression()

start = time.time() #Thời gian bắt đầu tính toán

#Train
logreg.fit(X_train, Y_train)
print('Đã học xong trong:', time.time()-start, ' s')

#Predict
Y_pred = logreg.predict(X_test)
print('Đã dự đoán xong')

In [6]:
#Trực quan hóa sử dụng Radviz
from pandas.plotting import radviz

fig, ax = plt.subplots(1,2, figsize=(13, 5))
# plt.figure(figsize=(15,10))
radviz(test, "species", ax=ax[0], colormap = 'tab10')
ax[0].set_title('TEST')

radviz(pred, "species", ax=ax[1], colormap = 'tab10')
ax[1].set_title('PRED')

plt.tight_layout();
plt.show()
# [test['species'] != 'Iris-setosa']

NameError: name 'plt' is not defined

In [ ]:
#Trực quan hóa sử dụng Radviz
from pandas.plotting import radviz

fig, ax = plt.subplots(1,2, figsize=(13, 5))
# plt.figure(figsize=(15,10))
radviz(test[test['species'] != 'Iris-setosa'], "species", ax=ax[0], colormap = 'tab10')
ax[0].set_title('TEST')

radviz(pred[pred['species'] != 'Iris-setosa'], "species", ax=ax[1], colormap = 'tab10')
ax[1].set_title('PRED')

plt.tight_layout();
plt.show()

In [ ]:
#Trực quan hóa sử dụng parallel_coordinates (biểu đồ bình phong)
from pandas.plotting import parallel_coordinates

fig, ax = plt.subplots(2,1, figsize=(10, 10))

parallel_coordinates(test, "species", ax=ax[0], colormap = 'tab10')
ax[0].set_title('TEST')
ax[0].set_xlabel('Features'); ax[0].set_ylabel('Features values')

parallel_coordinates(pred, "species", ax=ax[1], colormap = 'tab10')
ax[1].set_title('PRED')
ax[1].set_xlabel('Features'); ax[1].set_ylabel('Features values')

plt.tight_layout();
plt.show()

In [7]:
#Thư viện
from sklearn.tree import DecisionTreeClassifier

#Tạo model
dec_tree = DecisionTreeClassifier()

#fit, train
start = time.time()
dec_tree.fit(X_train,Y_train)
print('Đã học xong trong:', time.time()-start, ' s')

#dự đoán
y_pred = dec_tree.predict(X_test)
#Tạo bảng df để trực quan hóa
test = pd.concat([X_test, Y_test], axis=1)
Y_pred = pd.DataFrame(Y_pred, index=test.index, columns = ['species'])
pred = pd.concat([X_test, Y_pred], axis=1)
fig, ax = plt.subplots(1,2, figsize=(10, 5))
sns.scatterplot(data=test, x='petal_length', y='petal_width', hue='species', s=50, ax=ax[0])\
    .set(title='TEST');
sns.scatterplot(data=pred, x='petal_length', y='petal_width', hue='species', s=50, ax=ax[1])\
    .set(title='PRED');
plt.tight_layout();
plt.show()

NameError: name 'time' is not defined

In [8]:
#Thư viện
from sklearn.svm import SVC

#Tạo model
svc = SVC()

#fit
start = time.time()
svc.fit(X_train,Y_train)
print('Đã tính toán xong trong: ', time.time()-start, ' s')

#dự đoán
Y_pred = svc.predict(X_test)
#Tạo thành dataframe
test = pd.concat([X_test, Y_test], axis=1)
Y_pred = pd.DataFrame(Y_pred, index=test.index, columns = ['species'])
pred = pd.concat([X_test, Y_pred], axis=1)

NameError: name 'time' is not defined

In [ ]:
#Thư viện
from sklearn.naive_bayes import GaussianNB

#Tạo model
nb = GaussianNB()

#fit
start = time.time()
nb.fit(X_train,Y_train)
print('Đã tính toán xong trong: ', time.time()-start, ' s')

#dự đoán
Y_pred = nb.predict(X_test)

In [10]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
train = pd.read_csv('mobile train.csv')
train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [13]:
test = pd.read_csv('mobile test.csv')
test

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1700,1,1.9,0,0,1,54,0.5,170,...,17,644,913,2121,14,8,15,1,1,0
996,997,609,0,1.8,1,0,0,13,0.9,186,...,2,1152,1632,1933,8,1,19,0,1,1
997,998,1185,0,1.4,0,1,1,8,0.5,80,...,12,477,825,1223,5,0,14,1,0,0
998,999,1533,1,0.5,1,0,0,50,0.4,171,...,12,38,832,2509,15,11,6,0,1,0
999,1000,1270,1,0.5,0,4,1,35,0.1,140,...,19,457,608,2828,9,2,3,1,0,1